node {
    ansiColor('xterm') {
        env.PATH = '/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/opt/aws/bin:/home/ec2-user/.local/bin:/home/ec2-user/bin'

        stage('Checkout')
        checkout scm

        stage('Build')

        stage('API Test')

        stage('Integration Test')

        stage('Publish')
        sh '''
          zip index.zip index.js
          aws lambda  update-function-code --region eu-west-1 --function-name  sophia --zip-file fileb://index.zip
        '''
    }
}
